//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROLES
    {
        public ROLES()
        {
            this.PERMISSIONS = new HashSet<PERMISSIONS>();
            this.USERS = new HashSet<USERS>();
        }
    
        public int RoleId { get; set; }
        public System.DateTime LastModified { get; set; }
        public bool IsSysAdmin { get; set; }
        public string RoleDescription { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<PERMISSIONS> PERMISSIONS { get; set; }
        public virtual ICollection<USERS> USERS { get; set; }
    }
}
