//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SIC_NS_LOCALEntities : DbContext
    {
        public SIC_NS_LOCALEntities()
            : base("name=SIC_NS_LOCALEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public DbSet<Alarma> Alarma { get; set; }
        public DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public DbSet<Modulo> Modulo { get; set; }
        public DbSet<PERMISSIONS> PERMISSIONS { get; set; }
        public DbSet<ROLES> ROLES { get; set; }
        public DbSet<Sitio> Sitio { get; set; }
        public DbSet<SubMenus> SubMenus { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<TipoDeAlarma> TipoDeAlarma { get; set; }
        public DbSet<TipoSitio> TipoSitio { get; set; }
        public DbSet<USERS> USERS { get; set; }
        public DbSet<Contents> Contents { get; set; }
        public DbSet<Menu> Menu { get; set; }
    }
}
