//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sitio
    {
        public long id { get; set; }
        public string Nombre { get; set; }
        public string URL { get; set; }
        public long IdTipoSitio { get; set; }
        public string Descripcion { get; set; }
        public bool Activo { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public long IdUsuarioCreador { get; set; }
        public long IdUsuarioCreadorHistorial { get; set; }
        public Nullable<long> IdSubMenuPadre { get; set; }
        public Nullable<long> IdModulo { get; set; }
    
        public virtual TipoSitio TipoSitio { get; set; }
    }
}
