//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoDeAlarma
    {
        public TipoDeAlarma()
        {
            this.Alarma = new HashSet<Alarma>();
        }
    
        public int ID { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<Alarma> Alarma { get; set; }
    }
}
