//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoSitio
    {
        public TipoSitio()
        {
            this.Sitio = new HashSet<Sitio>();
        }
    
        public long Id { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public bool Activo { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public long IdUsuarioCreador { get; set; }
        public long IdUsuarioCreadorHistorial { get; set; }
    
        public virtual ICollection<Sitio> Sitio { get; set; }
    }
}
